[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"

# Activates recommended rule sets
lint.select = [
  "E",     # Errors
  "F",     # Pyflakes
  "I",     # Import sorting
  "UP",    # Pyupgrade
  "B",     # Bugbear
]

lint.ignore = [
  "E501",  # Ignore line too long (optional)
]

# Exclude files and folders
exclude = [
  ".venv",
  "mlruns",
]

[tool.ruff.format]
quote-style = "double"     # can be 'single'
indent-style = "space"
line-ending = "auto"
