site_name: "Documentation du projet CI/CD IA"
site_description: "Mise en place d’un pipeline CI/CD avec backend, frontend, MLflow et déploiement Azure"
site_author: "Chaima"

docs_dir: "docs_content"


theme:
  name: material

nav:
  - Accueil: index.md
  - Backend:
      - API: backend/api.md
      - Modèle: backend/model.md
      - Tests: backend/tests.md
  - Frontend:
      - App: frontend/app.md
  - CI/CD:
      - Pipeline: cicd/pipeline.md
      - Docker: cicd/docker.md
  - MLflow: mlflow/tracking.md
  - Deploy:
      - Azure: deploy/azure.md
      - DockerHub: deploy/dockerhub.md


