name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MODEL_DIR: backend/model
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      EXPERIMENT_NAME: "ML CICD Pipeline Core"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install ruff

    - name: Lint code with Ruff
      run: ruff check backend/ frontend/

    - name: Run backend tests
      run: pytest backend/tests/

    - name: Train model
      run: python backend/ml/train.py

    - name: Install MkDocs
      run: |
        pip install mkdocs mkdocs-material
        mkdocs gh-deploy --force

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build backend Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest backend/

    - name: Build frontend Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest frontend/

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest