name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:

    # 1️ Récupérer le code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️ Installer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3️ Installer dépendances backend
    - name: Install backend dependencies
      run: |
        pip install -r backend/requirements.txt
        pip install pytest

    # 4️ Lancer les tests
    - name: Run backend tests
      run: pytest backend/tests

    # 5️ Installer MkDocs + déployer documentation
    - name: Install MkDocs
      run: pip install mkdocs mkdocs-material

    - name: Deploy documentation
      working-directory: docs
      run: mkdocs gh-deploy --force

    # 6️ Connexion DockerHub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CHAIMA425 }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 7️ Build images backend & frontend
    - name: Build backend Docker image
      run: docker build -t ${{ secrets.CHAIMA425 }}/backend-app:latest backend/

    - name: Build frontend Docker image
      run: docker build -t ${{ secrets.CHAIMA425 }}/frontend-app:latest frontend/

    # 8️ Push images
    - name: Push Docker images
      run: |
        docker push ${{ secrets.CHAIMA425 }}/backend-app:latest
        docker push ${{ secrets.CHAIMA425 }}/frontend-app:latest